[custom.all.rio]
type   = "local"
path   = "."
ipkg   = "rio.ipkg"
test   = "test/test.ipkg"

[custom.all.rio-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.quantifiers-extra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-quantifiers-extra"
commit = "latest:main"
ipkg   = "quantifiers-extra.ipkg"

[custom.all.filepath]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-filepath"
commit = "latest:main"
ipkg   = "filepath.ipkg"
